import {
  Dealership,
  EarnMethod,
  MaintenanceRecommendation,
  OnboardingStep,
  Reward,
  RewardTransaction,
  ServiceRecord,
  TierDefinition,
  User,
  Vehicle,
} from "../types";
import { colors } from "./theme";

export const groupMembers = [
  "Milton Cezar Bacanieski - RM 555206",
  "Victorio Bastelli - RM 554723",
  "Lorenzo Mangini - RM 554901",
  "Vitor Bebiano - RM 555026",
];

export const mockUser: User = {
  id: "user-001",
  name: "Carlos Eduardo",
  email: "carlos.eduardo@email.com",
  cpf: "***.***.***-84",
  phone: "(11) 9 8765-4321",
  points: 1850,
  tier: "Prata",
  memberSince: "2022-03-15",
  avatar: "CE",
};

export const mockVehicles: Vehicle[] = [
  {
    id: "v-001",
    brand: "Ford",
    model: "Ranger XLS",
    version: "2.2 Diesel 4x4",
    year: 2022,
    plate: "BRA-2E19",
    mileage: 42500,
    fuelType: "Diesel",
    color: "Branco Artico",
    chassi: "9BFZZZAAXNB123456",
    healthScore: 78,
    lastService: "2024-09-10",
    nextService: "2025-03-10",
    systems: {
      motor: 92,
      freios: 78,
      pneus: 65,
      suspensao: 88,
      arCondicionado: 95,
      fluidos: 70,
    },
  },
  {
    id: "v-002",
    brand: "Ford",
    model: "Territory Titanium",
    version: "1.5 EcoBoost",
    year: 2023,
    plate: "GHJ-4K77",
    mileage: 18200,
    fuelType: "Flex",
    color: "Cinza Carbonizado",
    chassi: "9BFZZZBBYNC654321",
    healthScore: 94,
    lastService: "2024-11-20",
    nextService: "2025-05-20",
    systems: {
      motor: 98,
      freios: 96,
      pneus: 88,
      suspensao: 95,
      arCondicionado: 92,
      fluidos: 94,
    },
  },
];

export const mockDealerships: Dealership[] = [
  {
    id: "d-001",
    name: "Ford Saraiva - Tatuape",
    address: "Rua Tuiuti, 2450",
    neighborhood: "Tatuape",
    city: "Sao Paulo",
    state: "SP",
    cep: "03307-000",
    distanceKm: 3.8,
    rating: 4.7,
    availableSlots: 8,
    phone: "(11) 2090-4500",
  },
  {
    id: "d-002",
    name: "Ford Anhangabau - Centro",
    address: "Av. Sao Joao, 1220",
    neighborhood: "Centro",
    city: "Sao Paulo",
    state: "SP",
    cep: "01036-100",
    distanceKm: 6.2,
    rating: 4.5,
    availableSlots: 5,
    phone: "(11) 3120-1100",
  },
  {
    id: "d-003",
    name: "Ford Morumbi",
    address: "Av. Roque Petroni Junior, 1089",
    neighborhood: "Morumbi",
    city: "Sao Paulo",
    state: "SP",
    cep: "04707-000",
    distanceKm: 11.4,
    rating: 4.8,
    availableSlots: 12,
    phone: "(11) 5180-8800",
  },
  {
    id: "d-004",
    name: "Ford Caminho - Vila Leopoldina",
    address: "Rua Guaipa, 1444",
    neighborhood: "Vila Leopoldina",
    city: "Sao Paulo",
    state: "SP",
    cep: "05089-001",
    distanceKm: 9.1,
    rating: 4.4,
    availableSlots: 7,
    phone: "(11) 3649-9000",
  },
  {
    id: "d-005",
    name: "Ford Mix - Santo Amaro",
    address: "Av. Adolfo Pinheiro, 1800",
    neighborhood: "Santo Amaro",
    city: "Sao Paulo",
    state: "SP",
    cep: "04734-004",
    distanceKm: 14.6,
    rating: 4.2,
    availableSlots: 4,
    phone: "(11) 5525-7000",
  },
];

export const mockServices: ServiceRecord[] = [
  {
    id: "s-001",
    vehicleId: "v-001",
    vehicleName: "Ranger XLS",
    type: "Revisao preventiva 40.000 km",
    date: "2024-09-10",
    time: "10:00",
    dealershipId: "d-001",
    dealershipName: "Ford Saraiva - Tatuape",
    mileage: 40120,
    cost: 1290,
    status: "Concluido",
    notes: "Revisao com troca de filtros e diagnostico eletronico.",
    details: [
      { label: "Oleo", value: "Motorcraft 5W30" },
      { label: "Filtro", value: "Oleo, ar e combustivel" },
      { label: "Checklist", value: "128 itens aprovados" },
    ],
  },
  {
    id: "s-002",
    vehicleId: "v-002",
    vehicleName: "Territory Titanium",
    type: "Troca de oleo",
    date: "2024-11-20",
    time: "14:00",
    dealershipId: "d-003",
    dealershipName: "Ford Morumbi",
    mileage: 17200,
    cost: 520,
    status: "Concluido",
    details: [
      { label: "Oleo", value: "EcoBoost recomendado" },
      { label: "Inspecao", value: "Sem anomalias" },
    ],
  },
  {
    id: "s-003",
    vehicleId: "v-001",
    vehicleName: "Ranger XLS",
    type: "Rotacao de pneus",
    date: "2024-06-05",
    time: "09:00",
    dealershipId: "d-004",
    dealershipName: "Ford Caminho - Vila Leopoldina",
    mileage: 36500,
    cost: 240,
    status: "Concluido",
    details: [
      { label: "Pneus", value: "Rodizio cruzado" },
      { label: "Balanceamento", value: "Executado" },
    ],
  },
  {
    id: "s-004",
    vehicleId: "v-002",
    vehicleName: "Territory Titanium",
    type: "Revisao preventiva 10.000 km",
    date: "2024-04-18",
    time: "11:00",
    dealershipId: "d-002",
    dealershipName: "Ford Anhangabau - Centro",
    mileage: 10250,
    cost: 890,
    status: "Concluido",
    details: [
      { label: "Diagnostico", value: "Sistema EcoBoost normal" },
      { label: "Atualizacao", value: "Software Sync validado" },
    ],
  },
  {
    id: "s-005",
    vehicleId: "v-001",
    vehicleName: "Ranger XLS",
    type: "Inspecao de freios",
    date: "2024-01-12",
    time: "15:00",
    dealershipId: "d-001",
    dealershipName: "Ford Saraiva - Tatuape",
    mileage: 32800,
    cost: 410,
    status: "Concluido",
    details: [
      { label: "Pastilhas", value: "Meia vida" },
      { label: "Fluido", value: "Dentro do prazo" },
    ],
  },
  {
    id: "s-006",
    vehicleId: "v-002",
    vehicleName: "Territory Titanium",
    type: "Alinhamento e balanceamento",
    date: "2023-12-08",
    time: "16:00",
    dealershipId: "d-005",
    dealershipName: "Ford Mix - Santo Amaro",
    mileage: 8400,
    cost: 360,
    status: "Concluido",
    details: [
      { label: "Alinhamento", value: "Computadorizado" },
      { label: "Teste", value: "Rodagem aprovada" },
    ],
  },
  {
    id: "s-007",
    vehicleId: "v-001",
    vehicleName: "Ranger XLS",
    type: "Revisao preventiva 50.000 km",
    date: "2026-06-08",
    time: "10:00",
    dealershipId: "d-001",
    dealershipName: "Ford Saraiva - Tatuape",
    mileage: 50000,
    status: "Confirmado",
    notes: "Levar documento do veiculo.",
    details: [
      { label: "Estimativa", value: "2h30 de atendimento" },
      { label: "Consultor", value: "Paula Martins" },
    ],
  },
  {
    id: "s-008",
    vehicleId: "v-002",
    vehicleName: "Territory Titanium",
    type: "Recall e diagnostico Sync",
    date: "2026-07-02",
    time: "14:00",
    dealershipId: "d-003",
    dealershipName: "Ford Morumbi",
    mileage: 20500,
    status: "Agendado",
    details: [
      { label: "Campanha", value: "Atualizacao preventiva" },
      { label: "Duracao", value: "1h30" },
    ],
  },
];

export const maintenanceRecommendations: MaintenanceRecommendation[] = [
  {
    id: "m-001",
    vehicleId: "v-001",
    icon: "engine",
    name: "Troca de oleo",
    dueMileage: 45000,
    urgency: "Alta",
    description: "O motor da Ranger esta perto do intervalo recomendado.",
  },
  {
    id: "m-002",
    vehicleId: "v-001",
    icon: "car-tire-alert",
    name: "Pneus",
    dueDate: "2026-06-12",
    urgency: "Media",
    description: "Sulcos pedem verificacao na proxima visita.",
  },
  {
    id: "m-003",
    vehicleId: "v-002",
    icon: "air-conditioner",
    name: "Higienizacao do ar",
    dueDate: "2026-06-25",
    urgency: "Baixa",
    description: "Recomendado antes do inverno.",
  },
  {
    id: "m-004",
    vehicleId: "v-002",
    icon: "car-brake-alert",
    name: "Inspecao de freios",
    dueMileage: 20000,
    urgency: "Media",
    description: "Checklist preventivo para uso urbano intenso.",
  },
];

export const mockRewardTransactions: RewardTransaction[] = [
  {
    id: "rt-001",
    date: "2026-05-10",
    description: "Revisao na rede oficial",
    points: 200,
    type: "earn",
  },
  {
    id: "rt-002",
    date: "2026-04-29",
    description: "Avaliacao de atendimento",
    points: 50,
    type: "earn",
  },
  {
    id: "rt-003",
    date: "2026-03-18",
    description: "Resgate: cupom de acessorios",
    points: -300,
    type: "redeem",
  },
  {
    id: "rt-004",
    date: "2026-02-25",
    description: "Troca de oleo",
    points: 100,
    type: "earn",
  },
  {
    id: "rt-005",
    date: "2026-01-13",
    description: "Indicacao de amigo",
    points: 150,
    type: "earn",
  },
  {
    id: "rt-006",
    date: "2025-12-22",
    description: "Perfil completo",
    points: 30,
    type: "earn",
  },
];

export const earnMethods: EarnMethod[] = [
  { id: "e-001", icon: "tools", title: "Revisao na rede oficial", points: 200 },
  { id: "e-002", icon: "oil", title: "Troca de oleo", points: 100 },
  { id: "e-003", icon: "account-plus", title: "Indicar amigo", points: 150 },
  { id: "e-004", icon: "star-check", title: "Avaliar atendimento", points: 50 },
  { id: "e-005", icon: "account-check", title: "Completar perfil", points: 30 },
];

export const redeemableRewards: Reward[] = [
  {
    id: "r-001",
    icon: "percent",
    title: "10% desconto revisao",
    description: "Cupom para a proxima revisao preventiva.",
    pointsNeeded: 500,
    category: "discount",
  },
  {
    id: "r-002",
    icon: "spray-bottle",
    title: "Kit limpeza Ford",
    description: "Kit oficial para cuidados externos e internos.",
    pointsNeeded: 800,
    category: "product",
  },
  {
    id: "r-003",
    icon: "oil",
    title: "Troca de oleo gratis",
    description: "Servico completo em concessionaria participante.",
    pointsNeeded: 1200,
    category: "service",
  },
  {
    id: "r-004",
    icon: "clipboard-check",
    title: "Inspecao gratuita",
    description: "Checklist completo de seguranca.",
    pointsNeeded: 1500,
    category: "service",
  },
  {
    id: "r-005",
    icon: "car-seat",
    title: "Desconto acessorios",
    description: "Beneficio para itens originais Ford.",
    pointsNeeded: 2000,
    category: "discount",
  },
  {
    id: "r-006",
    icon: "coffee",
    title: "Sala premium",
    description: "Atendimento prioritario enquanto aguarda.",
    pointsNeeded: 2400,
    category: "experience",
  },
];

export const tierDefinitions: TierDefinition[] = [
  { tier: "Bronze", min: 0, max: 999, color: "#B87333" },
  { tier: "Prata", min: 1000, max: 2499, color: "#C0C0C0" },
  { tier: "Ouro", min: 2500, max: 4999, color: colors.warning },
  { tier: "Platinum", min: 5000, color: "#E5E4E2" },
];

export const onboardingSteps: OnboardingStep[] = [
  {
    id: "onboarding-001",
    title: "Mantenha seu Ford em dia",
    description:
      "Acompanhe manutencoes, alertas e saude do veiculo em uma experiencia conectada com a rede oficial.",
    icon: "car-connected",
  },
  {
    id: "onboarding-002",
    title: "Historico completo na palma da mao",
    description:
      "Veja servicos realizados, custos, quilometragem e recomendacoes para preservar seu Ford.",
    icon: "clipboard-text-clock",
  },
  {
    id: "onboarding-003",
    title: "Ganhe pontos e resgate beneficios",
    description:
      "Use a rede autorizada, evolua no Ford+ e troque pontos por vantagens reais.",
    icon: "trophy-award",
  },
];

export const serviceTypeOptions = [
  "Revisao Preventiva",
  "Troca de Oleo",
  "Rotacao de Pneus",
  "Alinhamento",
  "Freios",
  "Inspecao Geral",
  "Recall",
  "Outro",
];

export const timeSlots = ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"];
